# ===========================================
# SiteFrame 生产环境 Podman Compose 配置
# ===========================================

version: '3.8'

# 明确指定项目名称，避免使用目录名
name: siteframe

services:
  # ===========================================
  # SiteFrame 应用服务
  # ===========================================
  siteframe-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: siteframe-app-prod
    restart: unless-stopped
    env_file: 
      - .env.production
      - .env.production.local
    ports:
      - "12380:3000"
    # depends_on:
      # - redis
    networks:
      - siteframe-network
    volumes:
      # 只挂载必要的数据目录
      - app_uploads:/app/public/uploads
      - app_logs:/app/logs
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 安全配置
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache
      - /app/.next/cache
    # 用户权限
    user: "1001:1001"
    # 环境变量覆盖
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1

  # Redis 服务已移除 - 项目暂时不使用缓存

  # ===========================================
  # 注意：Nginx 已移除，使用宿主机 Caddy 作为反向代理
  # ===========================================

# ===========================================
# 网络配置
# ===========================================
networks:
  siteframe-network:
    driver: bridge
    # 使用默认子网配置，让 Podman 自动分配
    # ipam:
    #   config:
    #     - subnet: 172.25.0.0/16

# ===========================================
# 数据卷配置
# ===========================================
volumes:
  # 应用数据
  app_uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/siteframe/uploads
  
  app_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/log/siteframe
  
  # Redis 数据卷已移除